import React from 'react';
import { useOperations } from '../context/OperationsContext';
import { calculateImpact } from '../utils/impact';
import { canMatchHeldParcel, canPlaceOnHold } from '../utils/hubConstraints';
import { formatINR } from '../utils/locale';
export const ConnectedEventBar:React.FC<{section:string}> = ({section})=>{
 const {events,selectedId,selectedEvent,setSelectedId,loading,error,scenarioResult,updateStatus,audit}=useOperations();
 if(loading)return <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-4"><div className="rounded-xl bg-white border p-3 text-xs text-slate-500">Loading shared cancellation context…</div></div>;
 if(error)return <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-4"><div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs text-rose-800">Shared event service unavailable: {error}. This panel cannot show event specific data.</div></div>;
 const impact=selectedEvent?calculateImpact(selectedEvent):null;
 const transition=selectedEvent?.status==='Matched'?'Execute reassignment':selectedEvent?.status==='On hold'?(canMatchHeldParcel(selectedEvent)?'Confirm compatible match':'Route to warehouse fallback'):selectedEvent?.status==='Approved'?(canPlaceOnHold(selectedEvent,events).allowed?'Place on hub hold':'Route to warehouse fallback'):selectedEvent&&canPlaceOnHold(selectedEvent,events).allowed?'Approve recommendation':'Route to warehouse fallback';
 return <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-4"><div className="rounded-xl border border-amber-200 bg-white p-3 flex flex-col gap-3"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div className="min-w-0"><div className="text-[10px] font-bold tracking-wide text-amber-700">SHARED EVENT CONTEXT · {section.toUpperCase()}</div><div className="text-xs font-semibold mt-1">{selectedEvent?`${selectedEvent.id} · ${selectedEvent.product} · ${selectedEvent.status}`:'No event selected'}</div>{impact&&<div className="text-[10px] text-slate-500 mt-1">Estimate only · conventional {formatINR(impact.conventional.costInr)} vs recovery {formatINR(impact.smart.costInr)} · up to {impact.savings.distanceKm.toFixed(1)} km potential avoided</div>}{scenarioResult&&<div className="text-[10px] text-amber-800 mt-1">Latest scenario: {scenarioResult}</div>}</div><label className="text-[10px] text-slate-500">Selected cancellation<select value={selectedId} onChange={e=>setSelectedId(e.target.value)} className="block mt-1 border border-slate-300 rounded-lg px-2 py-1.5 text-xs text-slate-900 w-full sm:min-w-64">{events.map(e=><option key={e.id} value={e.id}>{e.id} · {e.product}</option>)}</select></label></div>{selectedEvent&&<div className="flex flex-wrap items-center gap-2 border-t pt-2"><span className="text-[10px] text-slate-500">Shared action state</span><button onClick={async()=>{const ev=selectedEvent;let next:typeof ev.status='Approved';let actor:'OPERATOR'|'AI-ASSISTED'='OPERATOR';if(ev.status==='Matched')next='Executed';else if(ev.status==='On hold'){next=canMatchHeldParcel(ev)?'Matched':'Fallback';actor='AI-ASSISTED'}else if(ev.status==='Approved')next=canPlaceOnHold(ev,events).allowed?'On hold':'Fallback';else next=canPlaceOnHold(ev,events).allowed?'Approved':'Fallback';if(window.confirm(`${transition} for ${ev.id}?`))await updateStatus(next,actor)}} disabled={['Executed','Rejected','Fallback'].includes(selectedEvent.status)} className="px-2.5 py-1.5 bg-amber-400 rounded-lg text-[10px] font-bold disabled:opacity-40">{transition}</button><button onClick={async()=>{if(window.confirm(`Reject recommendation for ${selectedEvent.id}?`))await updateStatus('Rejected','OPERATOR')}} disabled={['Executed','Rejected'].includes(selectedEvent.status)} className="px-2.5 py-1.5 border rounded-lg text-[10px] font-semibold disabled:opacity-40">Reject</button><span className="text-[10px] text-slate-500">{audit.filter(x=>x.eventId===selectedEvent.id).length} audit entries · confirmed mock transitions only</span></div>}</div></section>;
};
